### ISSUE TITLE
remove roadmap route and related images

### ISSUE THREAD

**Issue by bkawk** [worbli/website#77]

**Comment by bkawk** [comment]
- [] Remove link from header
- [] Remove route
- [] Remove any images
- [] verify no other remnants exist
